### ISSUE TITLE
ChangeCount 함수의 이름이 불명확합니다.

### ISSUE THREAD

**Issue by clucle** [LeeDongGyu0831/ChatServer#1]
오히려 구현만으로 본다면, AddUserCount 가 될 것 같습니다. 의도를 명확하게 부탁드립니다!

https://github.com/LeeDongGyu0831/ChatServer/blob/bfce811f8ba81e485d9a1cbaa1758f8271d92352/Server/Server/RoomMgr.cpp#L135-L137

https://github.com/LeeDongGyu0831/ChatServer/blob/bfce811f8ba81e485d9a1cbaa1758f8271d92352/Server/Server/Room.cpp#L40-L47

**Comment by LeeDongGyu0831** [comment]
넵 수정하겠습니다
음수로도 증가하도록 하나의 함수로 엮고싶어서 이름을 어떻게 표현할지 애매했었습니다.

**Comment by clucle** [comment]
`ChangeCount` 에서 음수 여부 때문에 함수명을 변경하라는 것보다는,

함수명만으로는 의도를 파악하기 어려워서 말씀드렸습니다.

가장 간단하게는 `ChangeCount` 가 아닌 `ChangeCurrentUserCount` 나 `ChangeUserCount` 가 더 좋아보이고

함수 의도를 조금 더 명확히 하기 위함으로 예를 들면

```
public:
    CRoom::AddUserCount()
    {
        ChangeUserCount(1);
    }

    CRoom::SubUserCount()
    {
        ChangeUserCount(-1);
    }

private:
    CRoom::ChangeUserCount(int count)
    {
        // ... something
    }
```

room 에 한번에 여러명이 들어가거나 나갈 상황이 없다면 위와 같은식으로  하면,

유저가 추가, 제거 될 때 카운트가 바뀌는 것으로 이해하기 편해 보입니다.

**Comment by LeeDongGyu0831** [comment]
넵 정말 감사합니다!

**Comment by clucle** [comment]
이슈 클로즈합니다!
