### ISSUE TITLE
변수명이 모호합니다.

### ISSUE THREAD

**Issue by clucle** [LeeDongGyu0831/ChatServer#2]
m_mapClient 변수명으로 봤을 때, 클라이언트의 맵이라고 생각되지만 사실은 RoomNumber와 Clients 를 매핑합니다.

코드 일부를 참조하면 이런 식으로 사용 할 수 있을 것 같습니다.
```
unordered_map<int, list<CClient*>> MapRoomNumberToClients;
MapRoomNumberToClients m_mapRoomNumberToClients;
```

또한 `auto p` 가 어떤걸 의미하는지 코드에서 파악하기 어렵습니다.
```
auto p = m_mapClient.find(roomNumber); 
```

https://github.com/LeeDongGyu0831/ChatServer/blob/bfce811f8ba81e485d9a1cbaa1758f8271d92352/Server/Server/RoomMgr.cpp#L113-L115

**Comment by LeeDongGyu0831** [comment]
넵 수정하겠습니다 너무 간략하게 표시하려고 한 것 같습니다.

**Comment by clucle** [comment]
이슈 클로즈합니다!
