### ISSUE TITLE
Room 이 해야할 일을 RoomMgr 에서 모두 처리하는 것으로 보입니다.

### ISSUE THREAD

**Issue by clucle** [LeeDongGyu0831/ChatServer#3]
예를 들어 현재 구조에서 방안에서 채팅을 할 경우

RoomMgr( 이하 룸 매니저라 칭함 ) 에서 방 넘버로 클라이언트 목록을 얻은 뒤
해당 클라이언트에게 메세지를 Send 할 것으로 보입니다.

일반적으로 룸 매니저는 방에 대한 관리 ( 방 생성 등 )를 하고, 클라이언트 목록은 룸에서 관리합니다.

프로젝트 구조에 대해서 잘 생각해 보시기 바랍니다 ㅎ

**Comment by LeeDongGyu0831** [comment]
감사합니다 현재 저도 고민하고 있었던 문제라서 어떤식으로 변경할지 생각중이였습니다.
서버를 클래스로 나누어서 처음부터 하나하나 기능을 구현해본적이 없다보니 서버 구조를 어떻게 설계하고 구현할지
모호해서 기능 구현을 우선으로 하고 그 이후 감이 잡히면 리팩토링을 하는 식으로 하는 중이였습니다.

**Comment by clucle** [comment]
같이 과제하는 동기분들 또한 같은 고민을 했을 것으로 예상되어,

서로 상의하면서 진행하면 더욱 도움이 될 것 입니다.

저도 클라이언트 과제를 할 때 클라 동기분들의 도움을 받으며 진행했습니다 ㅎㅎ 화이팅!

이슈 클로즈합니다.
